### PR TITLE
Support exporting as environment variables

### LINKED ISSUE #42: Support exporting as environment variables
I would like to propose the addition of an option (`export-variables`) that exports the key value pairs as environment variables in addition to setting them as the output.

This makes it easier to use this action with steps that expect the values in environment variables, meaning that we don't need to write an intermediate step that takes the output and exports them as environment variables.

### PR DESCRIPTION
**Pull request by F21**
This PR adds the `export-variables` option that also exports the variables as environment variables.

Closes #42

### CODE REVIEW

**Comment by F21** [comment]
ping @falti

**Review by falti — CHANGES_REQUESTED** [review]
Please add a unit test that validates the new behavior, thanks!

**Comment by F21** [comment]
I tried adding a test for it, but it seems like it's not possible to mock GitHub Actions' `exportVariable`. It doesn't write to `process.env` but calls `::set-env` on the runner, so I am not sure how this can be tested.

**Comment by sionescu** [comment]
You can add test it by using it in a workflow and checking that the right env var is set.

**Comment by F21** [comment]
Great idea @sionescu , I added a test using GH Actions.

**Comment by falti** [comment]
Looks good @F21 - would you please update your branch from main, then I'll merge it.

**Comment by F21** [comment]
Done @falti 😄

**Review by falti — APPROVED** [review]

**Comment by sionescu** [comment]
Can it preserve the case when exporting as environment variables ?
I know that by convention action outputs are all lowercase, but environment variables used in shell scripts are more commonly uppercase.

**Comment by F21** [comment]
@sionescu It doesn't preserve the case as everything is lower-cased by `dotenv_action` in https://github.com/falti/dotenv-action/blob/master/dotenv_action.js#L16. I have an issue regarding the lower-casing in #44.

**Pull request merged**
